import { NextRequest, NextResponse } from 'next/server';

export async function GET(
  request: NextRequest,
  { params }: { params: { reportName: string } }
) {
  try {
    const { reportName } = params;
    
    // Decode the report name
    const decodedReportName = decodeURIComponent(reportName);
    
    // Generate sample content for the recent report
    const reportContent = generateRecentReportContent(decodedReportName);
    
    // Create a simple text file (in production, this would fetch the actual stored report)
    const buffer = Buffer.from(reportContent, 'utf-8');
    
    return new NextResponse(buffer, {
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename="${decodedReportName}.txt"`,
      },
    });
  } catch (error) {
    console.error('Download recent report error:', error);
    return NextResponse.json({ error: 'Failed to download report' }, { status: 500 });
  }
}

function generateRecentReportContent(reportName: string): string {
  const timestamp = new Date().toLocaleString();
  
  const baseContent = `
${reportName}
Downloaded on: ${timestamp}
Original Report Generated: December 2024

This is a previously generated patient report that has been requested for download.
The original report contains comprehensive patient data analysis and insights.

---

REPORT CONTENTS:
Patient Demographics and Statistics
Consultation History and Trends
Treatment Outcomes and Efficacy
Prescription Patterns and Adherence
Follow-up Status and Compliance
Referral Patterns and Outcomes
Risk Stratification Analysis
Quality Metrics and Performance Indicators

---

Generated by SwasthyaOS Reports System
For inquiries, contact: reports@swasthyaos.health
  `.trim();
  
  // Add specific content based on report type
  if (reportName.includes('Individual Patient')) {
    return baseContent + `

INDIVIDUAL PATIENT REPORT - DETAILED ANALYSIS:
Patient ID: P123456
Age Group: 45-65 years
Gender: Male
Risk Category: Medium

Consultation Summary:
- Total Consultations: 12
- Primary Diagnosis: Hypertension
- Treatment Plan: Medication + Lifestyle Changes
- Last Visit: December 15, 2024

Medication History:
- Current Medications: 3
- Adherence Rate: 85%
- Side Effects: None reported

Vital Signs Trend:
- Blood Pressure: Controlled (avg 135/85)
- Heart Rate: Normal (avg 72 bpm)
- BMI: 26.5 (slightly overweight)

Follow-up Schedule:
- Next Appointment: January 15, 2025
- Monitoring Required: Blood pressure check
- Risk Factors: Diet, Exercise compliance
    `;
  }
  
  if (reportName.includes('Follow-up Status')) {
    return baseContent + `

FOLLOW-UP STATUS REPORT - Q4 2024:
Period: October 1 - December 31, 2024
Total Patients Requiring Follow-up: 1,255

Follow-up Completion Rates:
- Completed: 1,067 (85.0%)
- Pending: 156 (12.4%)
- Overdue: 32 (2.6%)

By Risk Category:
High Risk: 89/89 (100% completion)
Medium Risk: 456/500 (91.2% completion)
Low Risk: 522/666 (78.4% completion)

Follow-up Methods Utilized:
- Phone Calls: 678 (63.5%)
- In-Person Visits: 234 (21.9%)
- Video Consultations: 155 (14.5%)

Average Response Times:
- High Risk: 1.2 days
- Medium Risk: 2.8 days
- Low Risk: 4.5 days
    `;
  }
  
  if (reportName.includes('Prescription')) {
    return baseContent + `

PRESCRIPTION ADHERENCE REPORT:
Analysis Period: Q4 2024
Total Prescriptions Analyzed: 2,145

Overall Adherence Rate: 91%

Adherence by Medication Class:
- Antihypertensives: 94%
- Antidiabetics: 89%
- Antibiotics: 96%
- Analgesics: 87%

Factors Affecting Adherence:
- Side Effects: 23% of non-adherent cases
- Cost: 18% of non-adherent cases
- Forgetfulness: 34% of non-adherent cases
- Complexity: 15% of non-adherent cases
- Other: 10% of non-adherent cases

Intervention Outcomes:
- Reminder System: +12% adherence improvement
- Patient Education: +8% adherence improvement
- Simplified Regimens: +15% adherence improvement
    `;
  }
  
  if (reportName.includes('Referral')) {
    return baseContent + `

REFERRAL PATTERN ANALYSIS:
Period: Q4 2024
Total Referrals: 324

Referral Destinations:
- Cardiology: 89 (27.5%)
- Orthopedics: 67 (20.7%)
- Neurology: 56 (17.3%)
- Gastroenterology: 45 (13.9%)
- Others: 67 (20.6%)

Referral Outcomes:
- Accepted: 281 (86.7%)
- Declined: 26 (8.0%)
- Pending: 17 (5.2%)

Average Waiting Times:
- Urgent: 1.8 days
- Routine: 6.7 days
- Elective: 14.2 days

Referral Quality Metrics:
- Information Completeness: 94%
- Appropriate Referrals: 89%
- Patient Satisfaction: 87%
    `;
  }
  
  return baseContent;
}
