import jsPDF from 'jspdf';

export interface PDFReportData {
  title: string;
  dateRange: string;
  generatedOn: string;
  content: string;
  metadata?: Record<string, any>;
}

export class PDFGenerator {
  private doc: jsPDF;
  private pageHeight: number;
  private pageWidth: number;
  private margin: number = 20;
  private lineHeight: number = 7;
  private currentY: number = 20;

  constructor() {
    this.doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });
    this.pageHeight = this.doc.internal.pageSize.height;
    this.pageWidth = this.doc.internal.pageSize.width;
  }

  generateReport(reportData: PDFReportData): Uint8Array {
    // Reset current position
    this.currentY = this.margin;

    // Add header
    this.addHeader(reportData.title, reportData.dateRange, reportData.generatedOn);

    // Add content
    this.addContent(reportData.content);

    // Add footer
    this.addFooter();

    return new Uint8Array(this.doc.output('arraybuffer'));
  }

  private addHeader(title: string, dateRange: string, generatedOn: string): void {
    // Title
    this.doc.setFontSize(20);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text(title.toUpperCase(), this.margin, this.currentY);
    this.currentY += 15;

    // Date range
    this.doc.setFontSize(12);
    this.doc.setFont('helvetica', 'normal');
    this.doc.text(`Date Range: ${dateRange}`, this.margin, this.currentY);
    this.currentY += 8;

    // Generated on
    this.doc.text(`Generated on: ${generatedOn}`, this.margin, this.currentY);
    this.currentY += 12;

    // Add line separator
    this.doc.setLineWidth(0.5);
    this.doc.line(this.margin, this.currentY, this.pageWidth - this.margin, this.currentY);
    this.currentY += 10;
  }

  private addContent(content: string): void {
    this.doc.setFontSize(11);
    this.doc.setFont('helvetica', 'normal');

    // Split content into lines
    const lines = content.split('\n');
    
    for (const line of lines) {
      if (this.shouldAddNewPage()) {
        this.addNewPage();
      }

      // Handle different formatting
      if (line.startsWith('===')) {
        this.addSectionHeader(line.replace('=', '').trim());
      } else if (line.startsWith('-')) {
        this.addBulletPoint(line.replace('-', '').trim());
      } else if (line.match(/^\d+\./)) {
        this.addNumberedItem(line);
      } else if (line.trim() === '') {
        this.currentY += 3;
      } else {
        this.addTextLine(line);
      }
    }
  }

  private addSectionHeader(text: string): void {
    if (this.shouldAddNewPage()) {
      this.addNewPage();
    }

    this.doc.setFont('helvetica', 'bold');
    this.doc.setFontSize(14);
    this.doc.text(text.toUpperCase(), this.margin, this.currentY);
    this.currentY += 10;

    this.doc.setFont('helvetica', 'normal');
    this.doc.setFontSize(11);
  }

  private addBulletPoint(text: string): void {
    if (this.shouldAddNewPage()) {
      this.addNewPage();
    }

    const bulletText = `• ${text}`;
    this.doc.text(bulletText, this.margin + 5, this.currentY);
    this.currentY += this.lineHeight;
  }

  private addNumberedItem(text: string): void {
    if (this.shouldAddNewPage()) {
      this.addNewPage();
    }

    this.doc.text(text, this.margin, this.currentY);
    this.currentY += this.lineHeight;
  }

  private addTextLine(text: string): void {
    if (this.shouldAddNewPage()) {
      this.addNewPage();
    }

    // Handle long lines by wrapping text
    const maxLineWidth = this.pageWidth - (2 * this.margin);
    const lines = this.doc.splitTextToSize(text, maxLineWidth);

    for (const line of lines) {
      if (this.shouldAddNewPage()) {
        this.addNewPage();
      }
      this.doc.text(line, this.margin, this.currentY);
      this.currentY += this.lineHeight;
    }
  }

  private addFooter(): void {
    const footerY = this.pageHeight - 15;
    
    this.doc.setFontSize(9);
    this.doc.setFont('helvetica', 'italic');
    this.doc.text(
      'Generated by SwasthyaOS Reports System',
      this.margin,
      footerY
    );
    this.doc.text(
      'For inquiries, contact: reports@swasthyaos.health',
      this.margin,
      footerY + 5
    );

    // Add page number
    const pageCount = (this.doc as any).internal.pages.length - 1;
    for (let i = 1; i <= pageCount; i++) {
      (this.doc as any).setPage(i);
      this.doc.text(
        `Page ${i} of ${pageCount}`,
        this.pageWidth - this.margin - 20,
        footerY
      );
    }
  }

  private shouldAddNewPage(): boolean {
    return this.currentY > (this.pageHeight - 40);
  }

  private addNewPage(): void {
    this.doc.addPage();
    this.currentY = this.margin;
  }
}

export function generatePDFReport(reportData: PDFReportData): Uint8Array {
  const generator = new PDFGenerator();
  return generator.generateReport(reportData);
}
