import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const { dateRange } = await request.json();
    
    // Generate audit trail content
    const auditTrailContent = generateAuditTrailContent(dateRange);
    
    // Create a CSV file for audit trail
    const buffer = Buffer.from(auditTrailContent, 'utf-8');
    
    return new NextResponse(buffer, {
      headers: {
        'Content-Type': 'text/csv',
        'Content-Disposition': `attachment; filename="audit-trail-${dateRange.start}-to-${dateRange.end}.csv"`,
      },
    });
  } catch (error) {
    console.error('Generate audit trail error:', error);
    return NextResponse.json({ error: 'Failed to generate audit trail' }, { status: 500 });
  }
}

function generateAuditTrailContent(dateRange: any): string {
  const timestamp = new Date().toLocaleString();
  
  // CSV Header
  const csvHeader = 'Timestamp,User ID,User Name,Action,Resource,IP Address,User Agent,Result,Details\n';
  
  // Generate sample audit trail entries
  const auditEntries = generateAuditEntries(dateRange);
  
  // CSV Footer/Summary
  const csvFooter = `
\n
,AUDIT TRAIL SUMMARY,
Report Generated,${timestamp},
Period,${dateRange.start} to ${dateRange.end},
Total Events,${auditEntries.length},
Successful Events,${auditEntries.filter(e => e.result === 'Success').length},
Failed Events,${auditEntries.filter(e => e.result === 'Failed').length},
,
Event Types,,
Data Access Events,${auditEntries.filter(e => e.action.includes('Access')).length},
Data Export Events,${auditEntries.filter(e => e.action.includes('Export')).length},
System Configuration Changes,${auditEntries.filter(e => e.action.includes('Configuration')).length},
Authentication Events,${auditEntries.filter(e => e.action.includes('Login')).length},
,
Top Users,,
${getTopUsers(auditEntries).join('\n')}
,
Top Resources,,
${getTopResources(auditEntries).join('\n')}
,
,
Generated by SwasthyaOS Audit Trail System
For inquiries, contact: audit@swasthyaos.health
`;
  
  return csvHeader + auditEntries.map(entry => 
    `"${entry.timestamp}","${entry.userId}","${entry.userName}","${entry.action}","${entry.resource}","${entry.ipAddress}","${entry.userAgent}","${entry.result}","${entry.details}"`
  ).join('\n') + csvFooter;
}

function generateAuditEntries(dateRange: any): any[] {
  const entries = [];
  const startDate = new Date(dateRange.start);
  const endDate = new Date(dateRange.end);
  const daysDiff = Math.ceil((endDate.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24));
  
  // Sample users
  const users = [
    { id: 'USR001', name: 'Dr. Rajesh Kumar' },
    { id: 'USR002', name: 'Dr. Priya Sharma' },
    { id: 'USR003', name: 'Asha (Frontline)' },
    { id: 'USR004', name: 'Hari (Frontline)' },
    { id: 'USR005', name: 'Admin User' },
    { id: 'USR006', name: 'Nurse Rani' },
    { id: 'USR007', name: 'Lab Technician' }
  ];
  
  // Sample actions
  const actions = [
    'Patient Record Access',
    'Patient Data Export',
    'System Configuration Change',
    'User Login',
    'User Logout',
    'Prescription Access',
    'Lab Result Access',
    'Report Generation',
    'Data Backup',
    'Security Settings Update'
  ];
  
  // Sample resources
  const resources = [
    'Patient Record - P123456',
    'Patient Record - P789012',
    'System Settings',
    'User Management',
    'Report Generator',
    'Database',
    'Audit Logs',
    'Security Configuration',
    'Backup System',
    'Patient Portal'
  ];
  
  // Generate random entries for each day
  for (let day = 0; day < Math.min(daysDiff, 30); day++) {
    const currentDate = new Date(startDate);
    currentDate.setDate(startDate.getDate() + day);
    
    // Generate 5-15 random events per day
    const eventsPerDay = Math.floor(Math.random() * 10) + 5;
    
    for (let event = 0; event < eventsPerDay; event++) {
      const user = users[Math.floor(Math.random() * users.length)];
      const action = actions[Math.floor(Math.random() * actions.length)];
      const resource = resources[Math.floor(Math.random() * resources.length)];
      const hour = Math.floor(Math.random() * 24);
      const minute = Math.floor(Math.random() * 60);
      const second = Math.floor(Math.random() * 60);
      
      const timestamp = new Date(currentDate);
      timestamp.setHours(hour, minute, second);
      
      const isSuccessful = Math.random() > 0.05; // 95% success rate
      
      entries.push({
        timestamp: timestamp.toISOString(),
        userId: user.id,
        userName: user.name,
        action: action,
        resource: resource,
        ipAddress: `192.168.1.${Math.floor(Math.random() * 254) + 1}`,
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        result: isSuccessful ? 'Success' : 'Failed',
        details: isSuccessful ? 
          `Successfully ${action.toLowerCase()} on ${resource}` : 
          `Failed to ${action.toLowerCase()} on ${resource} - Permission denied`
      });
    }
  }
  
  // Sort by timestamp
  entries.sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime());
  
  return entries;
}

function getTopUsers(entries: any[]): string[] {
  const userCounts: Record<string, number> = {};
  
  entries.forEach(entry => {
    userCounts[entry.userName] = (userCounts[entry.userName] || 0) + 1;
  });
  
  const sortedUsers = Object.entries(userCounts)
    .sort(([,a], [,b]) => (b as number) - (a as number))
    .slice(0, 5);
  
  return sortedUsers.map(([name, count]) => `,${name},${count} events`);
}

function getTopResources(entries: any[]): string[] {
  const resourceCounts: Record<string, number> = {};
  
  entries.forEach(entry => {
    resourceCounts[entry.resource] = (resourceCounts[entry.resource] || 0) + 1;
  });
  
  const sortedResources = Object.entries(resourceCounts)
    .sort(([,a], [,b]) => (b as number) - (a as number))
    .slice(0, 5);
  
  return sortedResources.map(([resource, count]) => `,${resource},${count} accesses`);
}
